# tmux-sensible
set -s escape-time 0 # Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -g history-limit 50000 # Increase scrollback buffer size from 2000 to 50000 lines
set -g display-time 4000 # Increase tmux messages display duration from 750ms to 4s
set -g status-interval 5 # Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g default-terminal "tmux-256color"
set -g status-keys emacs # Emacs key bindings in tmux command prompt (prefix + :) are better than vi keys, even for vim users
set -g focus-events on # Focus events enabled for terminals that support them
setw -g aggressive-resize on # Super useful when using "grouped sessions" and multi-monitor setup
# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

set -g @menus_trigger Space
run-shell "$Z4H/sneethe/tmux-menus/menus.tmux"

set -g @tmux-gruvbox 'dark256' # or 'dark', 'dark256', 'light', 'light256'
set -g pane-border-lines single

set -g base-index 1
set -g pane-base-index 1

set -g mode-keys vi
bind -T copy-mode-vi v send -X rectangle-off \; send -X begin-selection
bind -T copy-mode-vi V send -X rectangle-off \; send -X select-line
bind -T copy-mode-vi 'C-v' send -X begin-selection \; send -X rectangle-on
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind-key C-b
set -g prefix C-Space

# vim's definition of a horizontal/vertical split is reversed from tmux's
bind v split-window -h -c '#{pane_current_path}'
bind s split-window -v -c '#{pane_current_path}'
# Panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Prompt jumping
unbind-key -T copy-mode-vi C-n
unbind-key -T copy-mode-vi C-p
bind -T copy-mode-vi C-n send -X next-prompt
bind -T copy-mode-vi C-p send -X previous-prompt


set-option -g mouse on
# https://www.reddit.com/r/tmux/comments/tqmyzm/snippet_better_scrolling/
bind-key -n WheelUpPane \
  if-shell -F "#{alternate_on}" \
    "if-shell -F \"#{mouse_any_flag}\" \
      \"send-key -M\" \
      \"send-key -N 3 Up\"" \
  "copy-mode -e ; send-keys -X -N 3 scroll-up"
bind-key -n WheelDownPane \
  if-shell -F "#{alternate_on}" \
    "if-shell -F \"#{mouse_any_flag}\" \
      \"send-key -M\" \
      \"send-key -N 3 Down\"" \
    "if-shell -F \"#{pane_in_mode}\" \
      \"send-keys -X -N 3 scroll-down\""
bind-key -T copy-mode-vi WheelUpPane send-keys -X -N 3 scroll-up
bind-key -T copy-mode-vi WheelDownPane send-keys -X -N 3 scroll-down

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
if "test ! -d ~/.config/zsh/sneethe/tpm/plugins/tmux-sensible" \
   "run '~/.config/zsh/sneethe/tpm/plugins/tpm/bin/install_plugins'"
run "$HOME/.config/zsh/sneethe/tpm/plugins/tpm/tpm"
